<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_TP4</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f14c452c-de4e-4783-a541-ec29b9c7a271</testSuiteGuid>
   <testCaseLink>
      <guid>0ec2b6eb-0657-41b2-8977-f14b27634f3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-1-LoginValido</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a8121c7-08de-461a-991c-3cb644e77de9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2c22069-e67c-43ff-9253-beedff2b41c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3d7b181-f920-4a78-9d12-b868d6817097</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-2-A-LoginInvalidoPresionandoEnElBotónLoginConSoloCampoPasswordCompletado</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad227031-6b23-447f-b76c-fa5648e45b74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24bfd97e-4754-4566-8eaf-212c65a39637</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-2-B-LoginInvalidoPresionandoEnElBotónLoginConSoloCampoUsuarioCompletado</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de877cd0-ffa3-4783-89cb-41e0945bece5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>177d1d19-d84b-4dd6-8cb9-23135e0c6ccf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-3-LoginInvalido</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f2819c74-0011-4acb-b75e-effdcf8e47f9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_SauceDemo</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f2819c74-0011-4acb-b75e-effdcf8e47f9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USUARIO</value>
         <variableId>99aa36de-07a2-400a-a758-f5cf10e1ae1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f2819c74-0011-4acb-b75e-effdcf8e47f9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CLAVE</value>
         <variableId>416beb96-3978-48bb-a0b2-855812f582ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f2819c74-0011-4acb-b75e-effdcf8e47f9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>MENSAJE</value>
         <variableId>16c11d91-4734-48f1-aed6-1537ef264dec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f2819c74-0011-4acb-b75e-effdcf8e47f9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ARCHIVO</value>
         <variableId>d1a039ea-7321-44a4-9cdb-a520af23d5b1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
